### PR TITLE
Fix docker path

### LINKED ISSUE #11: How do I run Test from within Docker?
I would like to migrate from `vim-test` but it seems I'm missing something.
My development environment is running inside Docker, so the way to execute the tests is:
```bash
docker exec -it $(docker ps -n=-1 -q --filter name=cityoffer_phpfpm --format="{{.ID}}") vendor/bin/phpunit
```

but if I configure the `phpunit_cmd` like this
```lua
local neotest = require("neotest")
neotest.setup({
    adapters = {
        require('neotest-phpunit')({
            phpunit_cmd = function()
                return 'docker exec -it $(docker ps -n=-1 -q --filter name=phpfpm --format="{{.ID}}") vendor/bin/phpunit'
            end
        }),
    },
})
```
I'm getting this error
```
Invalid value for argument cmd: 'docker exec -it $(docker ps -n=-1 -q --filter name=phpfpm --format="{{.ID}}") vendor/bin/phpunit' is not executable
```

I also tried to substitute `$(docker ps -n=-1 -q --filter name=phpfpm --format="{{.ID}}")` with the real ID with no luck.
And also I tried to through a shell script and got high CPU usage without a running test (and without any errors)

So how do I execute tests inside Docker?

### PR DESCRIPTION
**Pull request by eerison**
Close #11

### CODE REVIEW

**Comment by eerison** [comment]
Screenshot 2023-11-14 at 16 09 14

I am investigating why test is passing and it is red on the left side (🔴 )

**Comment by eerison** [comment]
Hey @olimorris 

when I run the tests I can see this error in neotest.log

```
ERROR | 2023-11-14T17:25:13Z+0100 | ...e/nvim/lazy/neotest-phpunit/lua/neotest-phpunit/init.lua:126 | No test output file found: var/nvim/phpunit.output
```

do you have any idea why?

Note: this folder is visible into the container and host
Note 2: I guess it is still saving in the old path 🤔

**Comment by olimorris** [comment]
@eerison thanks for your work on this, looks really promising. Off the top of my head, I have no idea but will see if I can take a look in the coming weeks.

**Comment by eerison** [comment]
Ok just a update, the file is created into the folder, then the problem is when it is loaded.

probably it is getting from old path

**Comment by eerison** [comment]
> Ok just a update, the file is created into the folder, then the problem is when it is loaded.
> 
> probably it is getting from old path
> 
> Note 1: Ok the file is created in container and host, But I saw that output file it is adding full path `file="/app/test/...`

well I guess it is the issue, when I run test with relative path it create the output file with full path :'(

**Comment by eerison** [comment]
Hey @olimorris do you remember where this icon is handled?

**Pull request closed without merging**
